name: security
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: 3.16.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc:

  injectable: ^2.3.2
  get_it: ^7.6.0

  dio: ^5.3.4
  pretty_dio_logger:
  dartz:

  flutter_dotenv:
  collection: ^1.18.0
  package_info_plus: ^5.0.1
  go_router: ^12.1.1

  google_fonts: ^6.1.0
  eva_icons_flutter: ^3.1.0
  lottie: ^2.7.0

  cached_network_image: ^3.2.3

  flutter_screenutil: ^5.9.0
  permission_handler: ^11.1.0

  copy_with_extension: ^5.0.2
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  logger: ^2.0.2+1

  get_storage: ^2.1.1
  animate_do:
  pretty_animated_buttons:

  freezed_annotation: ^2.4.1
  mobile_scanner: ^3.5.4

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  build_runner: 2.4.6
  json_serializable: ^6.7.1
  copy_with_extension_gen: ^5.0.4
  freezed: ^2.4.1

  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^3.0.1
  dart_code_metrics_presets: ^2.6.0
  analyzer: ^6.3.0


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/image/
    - assets/lottie/